// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDChQhn1pfgzNX5N42ek_vrr3IAhDf1RIw',
    appId: '1:636843638005:web:9886d28ada9cfb481919bc',
    messagingSenderId: '636843638005',
    projectId: 'uniforums-fdafd',
    authDomain: 'uniforums-fdafd.firebaseapp.com',
    storageBucket: 'uniforums-fdafd.firebasestorage.app',
    measurementId: 'G-8JTD32P538',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSjk9JfIAN91KnXgdCMU1zlavpzhTTBzE',
    appId: '1:636843638005:android:0d68227c65edd3f81919bc',
    messagingSenderId: '636843638005',
    projectId: 'uniforums-fdafd',
    storageBucket: 'uniforums-fdafd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjrTGOL_aWjfChaD7Jq6YIBzRVfx43en8',
    appId: '1:636843638005:ios:7b3f14f0d952b2d11919bc',
    messagingSenderId: '636843638005',
    projectId: 'uniforums-fdafd',
    storageBucket: 'uniforums-fdafd.firebasestorage.app',
    iosBundleId: 'com.example.uniForums',
  );
}
